
#ifdef GENERATE_LOC_ON_SERVER
  #include "loc_generator_server_generation.h"  
  #include <io.h>
#else
  #include "loc_generator_mobile_generation.h"
#endif


/* Defines */
#define VERSIONFGPCONVERT  "27/03/2014"

//Return defines : errors due to FgpGenerator lib


#define LOC_GENERATOR_SUCCESS								FGP_GENERATION_SUCCESS
#define LOC_GENERATOR_NOT_CONFIGURED_PROPERLY				FGP_ERROR_NOT_READY						
#define LOC_GENERATOR_CANT_ALLOCATE_FILTER					FGP_ERROR_CANT_ALLOCATE_FILTER	
#define LOC_GENERATOR_CANT_CREATE_OUTPUT_FILE				FGP_ERROR_CANT_CREATE_OUTPUT_FILE		
#define LOC_GENERATOR_CANT_OPEN_DATABASE_FILE				FGP_ERROR_CANT_OPEN_DATABASE_FILE			
#define LOC_GENERATOR_ERROR_RETRIVING_POSITION_INFORMATION	FGP_ERROR_RETRIVING_POSITION_INFORMATION	
#define LOC_GENERATOR_INTERMED_PT_GENERATION_FAILED			FGP_ERROR_INTERMED_PT_GENERATION_FAILED		
#define LOC_GENERATOR_MEASURE_GENERATION_FAILED				FGP_ERROR_MEASURE_GENERATION_FAILED			
#define LOC_GENERATOR_DURING_DOTBIN_FILE_ACESS				FGP_ERROR_DURING_DOTBIN_FILE_ACESS			
#define LOC_GENERATOR_CANT_GENERATE_OTHER_FILES				FGP_ERROR_CANT_GENERATE_OTHER_FILES			


//Return defines : errors due to loc_generator wrapper
#define LOC_GENERATOR_OFFSET_DEFINE							20
#define LOC_GENERATOR_WRAPPER_CANT_ALLOCATE_FILTER			LOC_GENERATOR_CANT_ALLOCATE_FILTER - LOC_GENERATOR_OFFSET_DEFINE
#define LOC_GENERATOR_WRAPPER_NOT_CONFIGURED_PROPERLY		LOC_GENERATOR_NOT_CONFIGURED_PROPERLY - LOC_GENERATOR_OFFSET_DEFINE
#define LOC_GENERATOR_WRAPPER_CANT_GENERATE_OTHER_FILES		LOC_GENERATOR_CANT_GENERATE_OTHER_FILES - LOC_GENERATOR_OFFSET_DEFINE



#ifdef __APPLE__
static const double RSSI_THRESHOLD_FGP_STD = 8.0;
#else
static const double RSSI_THRESHOLD_FGP_STD = 8.0;
#endif
