#pragma once


// Package generator conf
#define DEFAULTPARAM_FGP_RELIABILITY_PERCENTAGE				50



// struct mapSettingsParam
#define DEFAULTPARAM_MAPSETTINGS_POSTECHNIQUE				0
#define DEFAULTPARAM_MAPSETTINGS_k							3
#define DEFAULTPARAM_MAPSETTINGS_FILTERTYPE					6
#define DEFAULTPARAM_MAPSETTINGS_DYNAMICS_USER				0.1
#define DEFAULTPARAM_MAPSETTINGS_V_MAX_USER					2.0
#define DEFAULTPARAM_MAPSETTINGS_SENSOR_NOISE				7
#define DEFAULTPARAM_MAPSETTINGS_N_FILTER					4
#define DEFAULTPARAM_MAPSETTINGS_FILTER_SLOPE				0.5
#define DEFAULTPARAM_MAPSETTINGS_MAPMATCHING_TECHNIQUE		0
#define DEFAULTPARAM_MAPSETTINGS_MARKER_SIZE				5
#define DEFAULTPARAM_MAPSETTINGS_NB_BEFORE_1st_FIX			1
#define DEFAULTPARAM_MAPSETTINGS_AZIMUTH					-1



// struct zoneOutParams 
#define DEFAULTPARAM_ZONEOUT_RATIO_WKNN_BLE					0.5
#define DEFAULTPARAM_ZONEOUT_RATIO_WKNN_WIFI				0.5
#define DEFAULTPARAM_ZONEOUT_THRESHOLD_RSSI_BLE				-95
#define DEFAULTPARAM_ZONEOUT_THRESHOLD_RSSI_WIFI			-95
#define DEFAULTPARAM_ZONEOUT_HYSTERESIS_ON					5
#define DEFAULTPARAM_ZONEOUT_HYSTERESIS_STOP				3

#define DEFAULTPARAM_ZONEOUT_RATIOS_WHEN_OFF				0
#define DEFAULTPARAM_ZONEOUT_THRESHOLDS_WHEN_OFF			-101



// struct wifiFilteringParams
#define DEFAULTPARAM_WFILTERING_ALPHA1_BLE					0.9//0.5
#define DEFAULTPARAM_WFILTERING_ALPHA2_BLE					0.2//0.1
#define DEFAULTPARAM_WFILTERING_RSSI_THRESHOLD_AUTOCORRECT	-100
#define DEFAULTPARAM_WFILTERING_RSSI_GARBAGE_DOWN			-100
#define DEFAULTPARAM_WFILTERING_RSSI_GARBAGE_UP				-30
#define DEFAULTPARAM_WFILTERING_DELTA_DB					16

#define DEFAULTPARAM_WFILTERING_ALPHAS_WHEN_OFF				1
#define DEFAULTPARAM_WFILTERING_USEiPHONE5FLAG_WHEN_OFF		1
#define DEFAULTPARAM_WFILTERING_USEiPHONE5FLAG_WHEN_ON		0
#define DEFAULTPARAM_WFILTERING_USE_FILTER_RSSI				1
